[extend]
useDefault = true
filter = '''
!attributes["path"].contains("Other/Resources/LocalTestServices/")
&& !attributes["path"].contains("Other/Resources/CA/")
&& !attributes["path"].contains("Other/Resources/DevelopmentCertificate/")
&& !attributes["path"].contains("/.vs/")
&& !attributes["path"].contains("/.angular/")
'''
