import os
from pathlib import Path
from ScriptCollection.GeneralUtilities import GeneralUtilities
from ScriptCollection.ScriptCollectionCore import ScriptCollectionCore

# The streams which the testcase records. The names have to be the ones in RecordedStreamVisualRegressionTests.
_names_of_the_streams: list[str] = ["TestStreamA", "TestStreamB"]

# For how many numbers a baseline-picture is created. It has to be at least the amount which
# BaselinePictures.AmountOfPreparedNumbers of the testcases states.
_amount_of_numbers: int = 10


def update_recorded_stream_baselines():
    """Creates the pictures which the testcases of the recorded streams compare against.

    The pictures are taken from a video which is generated by the same function which produces the streams
    themselves, not from a recording: what has to be compared is the picture of a stream, and generating it
    directly makes the baselines reproducible and independent of a running application."""
    current_file = str(Path(__file__).absolute())
    codeunit_folder = GeneralUtilities.resolve_relative_path("../../..", current_file)
    repository_folder = GeneralUtilities.resolve_relative_path("..", codeunit_folder)
    # The font of this repository is used and not one of the operating-system, so the pictures are the same on
    # every machine.
    font_file = os.path.join(repository_folder, "Other", "Resources", "Fonts", "Noto", "NotoSans_Condensed-Regular.ttf")
    GeneralUtilities.assert_file_exists(font_file)
    target_folder = os.path.join(codeunit_folder, "Other", "Resources", "RecordedStreamBaselines")
    GeneralUtilities.ensure_directory_exists(target_folder)
    sc = ScriptCollectionCore()
    temporary_folder = os.path.join(codeunit_folder, "Other", "Artifacts", "RecordedStreamBaselineGeneration")
    GeneralUtilities.ensure_directory_does_not_exist(temporary_folder)
    GeneralUtilities.ensure_directory_exists(temporary_folder)
    try:
        for name_of_the_stream in _names_of_the_streams:
            video_file = os.path.join(temporary_folder, f"{name_of_the_stream}.mp4")
            sc.create_test_stream_video(video_file, _amount_of_numbers, name_of_the_stream, font_file=font_file)
            for number in range(_amount_of_numbers):
                # The picture is taken in the middle of the second, so it is the picture which is shown during
                # the whole second and not one which lies on the moment the number changes.
                moment = number + 0.5
                target_file = os.path.join(target_folder, f"{name_of_the_stream}_{number}.png")
                sc.run_program_argsasarray("ffmpeg", ["-hide_banner", "-loglevel", "error", "-ss", str(moment), "-i", video_file, "-frames:v", "1", "-y", target_file], temporary_folder, throw_exception_if_exitcode_is_not_zero=True)
            GeneralUtilities.write_message_to_stdout(f"Created the baseline-pictures of {name_of_the_stream}.")
    finally:
        GeneralUtilities.ensure_directory_does_not_exist(temporary_folder)


if __name__ == "__main__":
    update_recorded_stream_baselines()
