version: "3.2"

services:
  ConSurv_reverseproxy:
    image: nginx:1.27.4
    container_name: "ConSurv_reverseproxy"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "../../DevelopmentCertificate:/Workspace/Certificates"
    ports:
      - "443:443"
    networks:
      - ConSurv_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
      
networks:
  ConSurv_net:
    external: true
