@startuml
title ConSurvBackend - Database structure (MariaDB)
hide circle
skinparam linetype ortho

entity "AccessToken" {
  * Value : varchar <<PK>>
  --
  ExpiredMoment : datetime <<NOT NULL>>
  UserId : varchar <<NOT NULL>>
}

entity "Cameras" {
  * Id : varchar <<PK>>
  --
  Certificate : varchar
  Enabled : tinyint <<NOT NULL>>
  Name : varchar <<NOT NULL>>
  ONVIFPassword : varchar
  ONVIFUrl : varchar
  ONVIFUsername : varchar
  RecordMode : tinyint <<NOT NULL>>
  StreamURL : varchar <<NOT NULL>>
  SupportsPTZViaONVIF : tinyint <<NOT NULL>>
}

entity "RefreshToken" {
  * Value : varchar <<PK>>
  --
  ExpiredMoment : datetime <<NOT NULL>>
  UserId : varchar <<NOT NULL>>
}

entity "Role_InheritedRoles" {
  * InheritedRoleId : varchar <<PK>>
  * RoleId : varchar <<PK>>
}

entity "Roles" {
  * Id : varchar <<PK>>
  --
  Name : varchar <<NOT NULL>>
}

entity "UserSettings" {
  * Key : varchar <<PK>>
  * UserId : varchar <<PK>>
  --
  Value : longtext <<NOT NULL>>
}

entity "User_Roles" {
  * RoleId : varchar <<PK>>
  * UserId : varchar <<PK>>
}

entity "Users" {
  * Id : varchar <<PK>>
  --
  EMailAddress : varchar
  Name : varchar <<NOT NULL>>
  PasswordHash : varchar
  RegistrationMoment : datetime <<NOT NULL>>
  TOTPActivated : tinyint
  TOTPSecretKey : varchar
  UserIsActivated : tinyint <<NOT NULL>>
  UserIsLocked : tinyint <<NOT NULL>>
}

"AccessToken" }o--|| "Users" : UserId
"RefreshToken" }o--|| "Users" : UserId
"Role_InheritedRoles" }o--|| "Roles" : InheritedRoleId
"Role_InheritedRoles" }o--|| "Roles" : RoleId
"User_Roles" }o--|| "Roles" : RoleId
"User_Roles" }o--|| "Users" : UserId
@enduml
