@startuml CodeUnits-Overview
title CodeUnits of ConSurv

[ConSurvBackend]
note as ConSurvBackendNote
  ConSurvBackend is the backend for ConSurv.
end note
ConSurvBackend .. ConSurvBackendNote

[ConSurvApp]
note as ConSurvAppNote
  ConSurvApp is an app-client for ConSurv.
end note
ConSurvApp .. ConSurvAppNote

[ConSurvFrontend]
note as ConSurvFrontendNote
  ConSurvBackend is the frontend for ConSurv.
end note
ConSurvFrontend .. ConSurvFrontendNote

[ConSurv]
note as ConSurvNote
  ConSurv is an IP-cam-management-system.
end note
ConSurv .. ConSurvNote

ConSurvApp --> ConSurvBackend
ConSurvFrontend --> ConSurvBackend
ConSurv --> ConSurvBackend
ConSurv --> ConSurvFrontend

@enduml