@startuml RuntimeViewFullTest
title Runtime-view full test

actor "User" as user
note as UserNote
  The user calls https://consurv.test.local:443 or http://consurv.test.local:8080
end note
user .. UserNote

[ConSurv (:443 and :8080)] as ConSurv
note as ConSurvNote
    Started via "task BaseExampleStart" (or shorter: "task beu").
    The domain can be changed using the commandline-parameter "--InitialDomain <domain>".
    Backend and frontend are running in the container.
end note 
ConSurv .. ConSurvNote

[Database (:5432)] as ConSurvDatabase
note as ConSurvDatabaseNote
    Database-container
end note 
ConSurvDatabase .. ConSurvDatabaseNote

user --> ConSurv
ConSurv --> ConSurvDatabase
@enduml
