services:
  consurv:
    container_name: consurv
    env_file: Variables.env
    image: consurv:3.0.16
    ports:
    - "443:443"
    volumes:
    - ./Volumes/consurv/Data:/Workspace/Data
    - ./Volumes/consurv/Configuration:/Workspace/Configuration
    - ./Volumes/consurv/Logs:/Workspace/Logs
    depends_on:
    - consurv_database
  consurv_database:
    container_name: consurv_database
    image: ${image_postgresql}
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: ConSurvDatabase
    ports:
      - "5432:5432"
    volumes:
      - ./Volumes/consurv_database/Data:/var/lib/postgresql/data
  consurv_database_administration:
    container_name: consurv_database_administration
    depends_on:
    - consurv_database
    image: ${image_adminer}
    ports:
    - 8080:8080
