version: "3.2"

services:
  consurv_database:
    container_name: "consurv_database"
    image: ${image_postgresql}
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: ConSurvDatabase
#      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./Volumes/ConSurvPostgreSQLData:/var/lib/postgresql/data
    networks:
      - consurv_net
    command: >
      postgres -c log_connections=on -c log_disconnections=on

  consurv_database_administration:
    image: ${image_adminer}
    container_name: "consurv_database_administration"
    ports:
      - 8080:8080
    depends_on:
      - consurv_database
    networks:
      - consurv_net

networks:
  consurv_net:
    external: true
