services:
  consurv_database:
    container_name: "consurv_database"
    image: ${image_postgresql}
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pa55w0rd
      POSTGRES_DB: ConSurvDatabase
#      PGDATA: /var/lib/postgresql/data
    expose:
      - "5432"
    volumes:
      - ./Volumes/ConSurvPostgreSQLData:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U user -d ConSurvDatabase || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 5s
    networks:
      - consurv_net
    command: >
      postgres -c log_connections=on -c log_disconnections=on

  consurv_database_administration:
    image: ${image_adminer}
    container_name: "consurv_database_administration"
    expose:
      - "8080"
    depends_on:
      - consurv_database
    networks:
      - consurv_net

networks:
  consurv_net:
    external: true
