version: '3.2'

services:

  continuoussurveillance:
    image: continuoussurveillance:0.1.0
    container_name: 'continuoussurveillance'
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - "./Volumes/Configuration:/Workspace/Configuration"
      - "./Volumes/Data:/Workspace/Data"
      - "./Volumes/Logs:/Workspace/Logs"
