services:
  consurv_database:
    container_name: "consurv_database"
    image: ${image_mariadb}
    expose:
      - "3306"
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: pa55w0rd
      MARIADB_ROOT_PASSWORD: R00tpa55w0rd
      MARIADB_DATABASE: ConSurvDatabase
    volumes:
      - ./Volumes/ConSurvMariaDBData:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -pR00tpa55w0rd || exit 1"]
      interval: 2s
      timeout: 2s
      retries: 20
      start_period: 5s
    networks:
      - consurv_net

  consurv_database_administration:
    image: ${image_adminer}
    container_name: "consurv_database_administration"
    expose:
      - "8080"
    networks:
      - consurv_net

networks:
  consurv_net:
    external: true
