name: buildpipeline
on:
  push:
    branches:
      - main
      - other/next-release
  workflow_dispatch:
jobs:
  build-pipeline:
    runs-on: [self-hosted, scriptcollection]
    container:
      image: aniondev/scbuilder:v1.2.0
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: update apt (temporary)
        run: apt update
      - name: install graphviz (temporary)
        run: apt install graphviz -y
      - name: Update scriptcollection (temporary)
        run: pip3 install scriptcollection --upgrade
      - name: Show scversion (temporary)
        run: scshowversion
      - name: Prepare build-pipeline
        run: scpreparebuildpipelineforgitlab
      - name: Build codeunits
        run: scbuildcodeunits -v 4 --assertnonewchanges
      - name: Install CycloneDX NPM
        run: npm install --global @cyclonedx/cyclonedx-npm
      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            ConSurv/Other/Artifacts
            ConSurvApp/Other/Artifacts
            ConSurvBackend/Other/Artifacts
            ConSurvFrontend/Other/Artifacts
          if-no-files-found: error
